### ISSUE TITLE
Removing keys from display configuration doesn't reset them to default

### ISSUE THREAD

**Issue by Saviq** [canonical/mir#2947]
Use e.g.:

```yaml
layouts:           
  default:         
    cards:         
    - card-id: 0   
      eDP-1:       
        scale: 2
```

If you remove `scale: 2`, it stays active, only when you change the value will it get applied, unless you start the server fresh.
