### ISSUE TITLE
Screenshot outputs weirdly shifted image.

### ISSUE THREAD

**Issue by DAVID9SE** [canonical/mir#3259]
Hi! 
I am using ubuntu frame for a kiosk. Everything went smoothly but now I am trying to implement screenshot-based sanity checks. When I call `ubuntu-frame.screenshot` the output image is shifted.
<img src=https://github.com/canonical/ubuntu-frame/assets/25270309/90beb919-a185-4d71-93d3-5d6f48ff0b1b width=50%>

I am using a 1920x1080@60.0 screen that is rotated so orientation is set to left.
The program running is wpe-webkit-mir-kiosk.

Thanks a lot in advance

**Comment by Saviq** [comment]
Reproducer:

```
# cat display.config
layouts:
  default:
    cards:
    - card-id: 0
      unknown-1:
        orientation: left
```

```
$ WAYLAND_DISPLAY=wayland-1 ./build-Debug/bin/miral-shell --display-config=static=$PWD/display.config --add-wayland-extensions all &
$ WAYLAND_DISPLAY=wayland-1 grim
```
