### ISSUE TITLE
`StaticDisplayConfig` only reacts once to unconfigured output connection

### ISSUE THREAD

**Issue by Saviq** [canonical/mir#3557]
Given the following `--display-config=static=` configuration:
```yaml
layouts:
  default:
    cards:
    - card-id: 0
```

Steps:
- start Mir with no outputs connected
- connect an output
- disconnect it
- connect another monitor

Expected:
- defaults get applied to the connected display and it lights up every time, at its preferred resolution

Current:
- the display only lights up once

On laptop, a version of the following can be used to reproduce, using a second output:
```yaml
layouts:
  default:
    cards:
    - card-id: 0
      eDP-1:
        state: disabled
```
