### ISSUE TITLE
`StaticDisplayConfig` only reacts once to extra output connection

### ISSUE THREAD

**Issue by Saviq** [canonical/mir#3558]
Given the following `--display-config=static=` configuration:
```yaml
layouts:
  default:
    cards:
    - card-id: 0
```

Steps:
- start Mir on your laptop
- connect an extra output
- disconnect it
- connect another monitor

Expected:
- defaults get applied to the connected display and it lights up every time, at its preferred resolution
